### ISSUE TITLE
Layer/Frame Onion Skinning

### ISSUE THREAD

**Issue by Ramzea** [DeflatedPickle/Rawky#14]
Animating would be made easier by ghosting previous layers. Simply showing previous layers as a semi-transparent image behind the current layer would allow the artist to see what needs to be changed to make the next frame. A toggle in the layer could be used to enable or disable the feature per-layer and maybe a way to changed the transparency level in the settings.

**Comment by DeflatedPickle** [comment]
A solution for changing the transparancyy level could be a right-click menu for the layer/frame with a sub-menu filled with pre-set transparancy options (as radio options).
