### ISSUE TITLE
Some Things You Might Want To Consider

### ISSUE THREAD

**Issue by Yangfu1000** [DeflatedPickle/Rawky#17]
Hi, I saw your program on Discord and wanted to add my suggestions. This seems like it definitely has potential as there are not many choices with regards to substantial pixel art programs that are offered for free. It still needs some work as a whole but it is still in alpha so that would be expected.

Features:

1. Instead of having the color shader base the shades off of 1 color- use 2 colors for the reference point and make a gradient between the different colors- and include a setting to allow for hue shifting in the gradient- I've never seen this done in any drawing program and only rarely in gradient makers- most just use the hue of the 2 reference colors and no shifting in between (If you need assistance with the hue shifting methods and how to scale them in a pleasing manner for a program- I can help)

2. Add color sliders as an option to pick colors RGB, HSL, and HSV- ones with precision where you can enter exact number values

3. Allow the scroll wheel on the mouse to adjust the different sliders if you hover over the area

4. Add number value settings for the different sliders to increase the precision of each setting

5. Add an easier way to move colors from the shader to the palette/library.

Bugs/Problems:

-Choosing a theme for the UI is particularly buggy and some options don't seem to change the theme

-The program feels clunky and slow on Windows 10

-The program gets flagged as a virus on Windows 10 (despite not containing malicious code from what I saw)

### To-Do
- [ ] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5 (as of b743bef and a2aa701)

**Comment by DeflatedPickle** [comment]
> Instead of having the color shader base the shades off of 1 color- use 2 colors for the reference

I've been planning on adding the typical 2 colour thing that most editors have, so I can add a quick toolbar to the shade widget to use 2 either colour. Or, step it up further than most editors and have the second colour show as a drop-down for many secondary colours and then you'd be able to change how it tweens between them, using a slider with muliple handles or some kind of curve graph.

> Add color sliders as an option to pick colors RGB, HSL, and HSV

The colour picker isn't mine, if you take a look at the credits. I've been planning to drop it and write a replacement, like I've done in [Sweet](https://github.com/DeflatedPickle/sweet/tree/colourpicker). But Swing doesn't have a native OpenGL widget, and LWJGL only provides one if you use LWJGL 2 and not LWJGL 3. There is a canvas for LWJGL 3, though adding it to the Gradle file causes IntelliJ IDEA to ignore all Gradle modules. Though I might be able to use the JOGL `GLCanvas` and then call LWJGL 3 methods.

> Allow the scroll wheel on the mouse to adjust the different sliders if you hover over the area

Good idea! I'm going to move most GUI things to an annotation-based system in preperation for when I add scripting, so this'll be added as a default to sliders.

> Add number value settings for the different sliders to increase the precision of each setting

I usually never add a a slider without a spinbox, but I was mildly lazy with them (as it's a mess to do listeners [see here](https://github.com/DeflatedPickle/FAOSDance/blob/master/src/main/kotlin/com/deflatedpickle/faosdance/util/GlobalValues.kt#L331-L413)). I'll mmove it to a class for the next update.

> Add an easier way to move colors from the shader to the palette/library

I actually hadn't thought about this, it shouldn't be at all hard to add a menu item to move all or just a selected colour over.

> Choosing a theme for the UI is particularly buggy

Indeed it is! I think I ought to do something before changing it. I haven't had much trouble when switching from themes, but it does throw many errors.

> The program feels clunky and slow on Windows 10

Why's that? I mainly develop and use it on Windows 10 and it seems perfectly fine.

> The program gets flagged as a virus on Windows 10

Windows 10 seems to flag everything that isn't on a whitelist as a virus, unless you turn off your virus protection.
