### ISSUE TITLE
Tile view overlap

### ISSUE THREAD

**Issue by sekwah41** [DeflatedPickle/Rawky#22]
When you do a larger texture it doesn't expand the tiled view it just draws at the same offsets causing overlapping textures.

**Comment by DeflatedPickle** [comment]
Thanks for reporting this, I haven't looked at the `TiledView` closely for ages. The culprit is the usages [here](https://github.com/DeflatedPickle/Rawky/blob/master/src/main/kotlin/com/deflatedpickle/rawky/component/TiledView.kt#L29-L32) of `16`, instead of the `PixelSize` columns and rows.
