### ISSUE TITLE
broken cursor rendering

### ISSUE THREAD

**Issue by UpcraftLP** [DeflatedPickle/Rawky#27]
for some reason my cursor is rendered 3 times
![image](https://user-images.githubusercontent.com/10714589/69846213-a6f78600-1273-11ea-83ec-ed8272491670.png)

Rawky Version: 0.9.1-alpha

**Comment by DeflatedPickle** [comment]
This is intended. You have 3 mouse tools, one for each button. It renders the tool icons to show that off. If you selected a different tool for the right button, like the eraser, you'd see the last icon change.

**Comment by UpcraftLP** [comment]
in that case maybe render the 2 additional tools smaller, and closer to the main one?
otherwise it just looks like a render bug, and is rather irritating at that

**Comment by DeflatedPickle** [comment]
They are rendered smaller, but the distancing is due to weird transforms, I think. Do you think it might be better if I rendered them in a circle? Might look nicer, at least.
