### ISSUE TITLE
clicking outside the pixel grid paints at last on-grid position

### ISSUE THREAD

**Issue by UpcraftLP** [DeflatedPickle/Rawky#28]
when you move the cursor outside of the valid draw area in the pixel grid and click, it paints the pixel at the last known position inside the draw area. Instead, it shouldn't draw at all.

Rawky Version: 0.9.1-alpha

Before:
![image](https://user-images.githubusercontent.com/10714589/69846302-e625d700-1273-11ea-92eb-e2a1d5220678.png)

After:
![image](https://user-images.githubusercontent.com/10714589/69846334-f938a700-1273-11ea-8fcc-ba1e58c3da82.png)

**Comment by DeflatedPickle** [comment]
This is one of those bugs that's really unimportant. Like, it doesn't negatively affect you in any way if it isn't fixed. So with stuff like this, I put it on a mental list and fix it when it's pointed out.
